services:
  service1:
    build: ./service_1
    container_name: service1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    expose:
      - "8001"
  service2:
    build: ./service_2
    container_name: service2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    expose:
      - "8002"
  nginx:
    build: ./nginx
    container_name: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "80:80"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
