services:
  service1:
    build: ./service_1
    container_name: service1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.24.1.11:8001/ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    expose:
      - "8001"
  service2:
    build: ./service_2
    container_name: service2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.24.1.11:8002/ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    expose:
      - "8002"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
